### ISSUE TITLE
What were tax brackets in assessment year 2017?

### ISSUE THREAD

**Issue by martinholmer** [TPRU-demo/pitaxcalc-demo#20]
The instructions for ITR-1 show the tax brackets for assessment year 2018(-19) .
Were the brackets the same for assessment year 2017(-18) or were they inflation indexed between 2017 and 2018?

**Comment by com1tpru** [comment]
No the tax brackets are not inflation indexed in India

**Comment by ADITPR** [comment]
There is no tax inflation bracket in India. So the tax logic will be different

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>Were the brackets the same for assessment year 2017(-18) or were they inflation indexed between 2017 and 2018?

@com1tpru and @ADITPR  answered above
